name: "Setup awesome-ci tooling"
description: "Setup awesome-ci as a CI tool in the latest stable version"
branding:
  color: blue
  icon: anchor
inputs:
  version:
    required: false
    description: "The version to use (default: 1.7.1)"
    default: "1.7.1"
runs:
  using: 'node20'
  main: 'dist/index.js'
