name: "Setup awesome-ci tooling"
description: "Setup awesome-ci as a CI tool in the latest stable version"
branding:
  color: blue
  icon: anchor
inputs:
  version:
    required: false
    description: "The version to use (default: 1.4.0)"
    default: "1.4.0"
runs:
  using: 'node16'
  main: 'dist/index.js'
